const ROOMS_WIDE = [
  "living_room",
  "kitchen",
  "hallway",
  "home_office",
  "private_office",
  "reception",
  "corridor",
  "open_office",
  "meeting_room",
  "dining_room",
  "bedroom",
  "storage",
  "other",
] as const;

const STYLES = ["functional", "minimal", "warm_modern", "architectural"] as const;

export const WL_LIGHTING_PRODUCTS = [
  {
    id: "wl-milano-s",
    name: "WL Milano S 7W 927 Phase Dim",
    brand: "WL",
    category: "tracklighting",
    articleNumber: "WL-MILANO-S",
    luminousFluxLumens: 650,
    powerWatts: 7,
    colourTemperatureKelvin: 2700,
    dimmingType: "Phase dim",
    cri: "90+",
    mountingTypes: ["track"],
    suitableRoomTypes: [...ROOMS_WIDE],
    suitableStylePresets: [...STYLES],
    beamAngleDegrees: 36,
    imageUrl: "/products/wl-milano-s.placeholder.svg",
    dimensions: { shape: "circle", diameterMm: 85 },
  },
  {
    id: "wl-milano-xl",
    name: "WL Milano XL 17W 927 Phase Dim",
    brand: "WL",
    category: "tracklighting",
    articleNumber: "WL-MILANO-XL",
    luminousFluxLumens: 2000,
    powerWatts: 17,
    colourTemperatureKelvin: 2700,
    dimmingType: "Phase dim",
    cri: "90+",
    mountingTypes: ["track"],
    suitableRoomTypes: [...ROOMS_WIDE],
    suitableStylePresets: [...STYLES],
    beamAngleDegrees: 36,
    imageUrl: "/products/wl-milano-xl.placeholder.svg",
    dimensions: { shape: "circle", diameterMm: 105 },
  },
  {
    id: "wl-palermo",
    name: "WL Palermo 25W 930 Adjustable",
    brand: "WL",
    category: "tracklighting",
    articleNumber: "WL-PALERMO",
    luminousFluxLumens: 3000,
    powerWatts: 25,
    colourTemperatureKelvin: 3000,
    cri: "90+",
    adjustable: true,
    mountingTypes: ["track"],
    suitableRoomTypes: [...ROOMS_WIDE],
    suitableStylePresets: [...STYLES, "custom"],
    beamAngleDegrees: 36,
    imageUrl: "/products/wl-palermo.placeholder.svg",
    dimensions: { shape: "circle", diameterMm: 110 },
  },
  {
    id: "wl-bari-small",
    name: "WL Bari Small 6W 930",
    brand: "WL",
    category: "downlight",
    articleNumber: "WL-BARI-S",
    luminousFluxLumens: 600,
    powerWatts: 6,
    colourTemperatureKelvin: 3000,
    cri: "90+",
    mountingTypes: ["recessed", "surface"],
    suitableRoomTypes: [...ROOMS_WIDE],
    suitableStylePresets: [...STYLES],
    beamAngleDegrees: 60,
    imageUrl: "/products/wl-bari-small.placeholder.svg",
    dimensions: { shape: "circle", diameterMm: 105 },
  },
  {
    id: "wl-bari-large",
    name: "WL Bari Large 25W 930",
    brand: "WL",
    category: "downlight",
    articleNumber: "WL-BARI-L",
    luminousFluxLumens: 2200,
    powerWatts: 25,
    colourTemperatureKelvin: 3000,
    cri: "90+",
    mountingTypes: ["recessed", "surface"],
    suitableRoomTypes: [...ROOMS_WIDE],
    suitableStylePresets: [...STYLES],
    beamAngleDegrees: 60,
    imageUrl: "/products/wl-bari-large.placeholder.svg",
    dimensions: { shape: "circle", diameterMm: 200 },
  },
  {
    id: "wl-gela-tube",
    name: "WL Gela Tube 6.7W 927",
    brand: "WL",
    category: "recessed_spot",
    articleNumber: "WL-GELA-TUBE",
    luminousFluxLumens: 500,
    powerWatts: 6.7,
    colourTemperatureKelvin: 2700,
    cri: "90+",
    mountingTypes: ["recessed"],
    suitableRoomTypes: [...ROOMS_WIDE],
    suitableStylePresets: [...STYLES],
    beamAngleDegrees: 36,
    imageUrl: "/products/wl-gela-tube.placeholder.svg",
    dimensions: { shape: "circle", diameterMm: 85 },
  },
  {
    id: "wl-spark-595",
    name: "WL Spark Inlegpaneel 595x595 CCT",
    brand: "WL",
    category: "led_panel",
    articleNumber: "WL-SPARK-595",
    luminousFluxLumens: 3600,
    powerWatts: 29,
    colourTemperatureKelvin: 4000,
    mountingTypes: ["recessed", "panel"],
    suitableRoomTypes: [...ROOMS_WIDE],
    suitableStylePresets: [...STYLES],
    beamAngleDegrees: 110,
    imageUrl: "/products/wl-spark-595.placeholder.svg",
    dimensions: { shape: "rectangle", widthMm: 595, lengthMm: 595 },
  },
  {
    id: "wl-spark-1195",
    name: "WL Spark Inlegpaneel 1195x295 CCT",
    brand: "WL",
    category: "led_panel",
    articleNumber: "WL-SPARK-1195",
    luminousFluxLumens: 3600,
    powerWatts: 29,
    colourTemperatureKelvin: 4000,
    mountingTypes: ["recessed", "panel"],
    suitableRoomTypes: [...ROOMS_WIDE],
    suitableStylePresets: [...STYLES],
    beamAngleDegrees: 110,
    imageUrl: "/products/wl-spark-1195.placeholder.svg",
    dimensions: { shape: "rectangle", widthMm: 295, lengthMm: 1195 },
  },
] as const;

export const WL_PRODUCT_IDS = new Set(
  WL_LIGHTING_PRODUCTS.map((product) => product.id),
);
